project: 
  type: website

website: 
  page-navigation: true
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  navbar:
    title: "Climate & Ecosystems Group"
    background: $navbar-bg
    logo: "images/noaa_logo.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/lmdewitt

    style: "docked"
    search: true

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    toc: true


filters:
  - include-files.lua
  - quarto

  
