project: 
  type: website

website: 
  page-navigation: true
  favicon: images/favicon.ico
  back-to-top-navigation: true  
  page-footer:
    border: true
    center:
      - text: "Website Owner"
        href: https://www.fisheries.noaa.gov/about/southwest-fisheries-science-center
      - text: "Contact"
        href: https://www.fisheries.noaa.gov/contact/southwest-fisheries-science-center
      - text: "NOAA"
        href: https://www.noaa.gov/
      - text: "Privacy Policy"
        href: https://www.noaa.gov/privacy.html
      - text: "Information Quality"
        href: https://www.noaa.gov/organization/information-technology/policy-oversight/information-quality
      - text: "Disclaimer"
        href: https://www.fisheries.noaa.gov/national/about-us/website-policies-and-disclaimers
    right:
      - text: "<img src='/images/logos/doc_logo_black.gif' style='height: 50px; width: auto;'/>"
        href: https://www.commerce.gov/
  navbar:
    title: "Climate & Ecosystems Group"
    background: $navbar-bg
    logo: "images/noaa_logo.png"
    favicon: images/favicon.ico
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/lmdewitt

    style: "docked"
    search: true
    left:
      - text: "About"
        href: about.qmd
      - text: "People"
        href: people.qmd
  sidebar:
    - style: "docked" 
      contents:
        - section: "Data"
          contents:
            - section: "Marine Heat Wave"
              contents:
                - text: "Latest Conditions"
                  href: projects/mhw/latest.qmd
                - text: "About"
                  href:  projects/mhw/about.qmd
                - text: "Previous Updates"
                  href: projects/mhw/prev.qmd
                - text: "Videos"
                  href: projects/mhw/videos.qmd
                - text: "Regional EEZ MHW"
                  href: projects/mhw/regional_eez.qmd
                - text: "References"
                  href: projects/mhw/refs.qmd

format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    link-external-newwindow: true
    toc: true

filters:
  - include-files.lua
  - quarto

language:
  en:
    listing-page-field-categories: "Collaborations" # Changes the sidebar & column header text
    listing-page-category-all: "All Projects"  # Optional: Changes the "All" button text
  
